version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

submodules:
  include: all
  recursive: true

sphinx:
   configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
    - requirements: requirements.txt