[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.8.0",
    "oldest-supported-numpy"
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/tests/test_toolbox.py"
skip = ["*musllinux*", "*-win32*"]
test-requires = "pytest"