[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.8.0",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/tests/test_toolbox.py"
skip = ["*musllinux*", "cp36-win*", "cp37-win*", "cp38-win*"]
test-requires = "pytest"