name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    - name: Checkout Empirical
      uses: actions/checkout@v3
      with:
        repository: devosoft/Empirical
        path: Empirical
        ref: MABE_devel
    - name: Checkout Catch
      uses: actions/checkout@v3
      with:
        repository: catchorg/Catch2
        path: Catch2
        ref: v2.x
    - name: make
      run: make test
